#!/usr/bin/env sh
set -eu

# Generates script/test/COVERAGE.md
#
# This script is intentionally POSIX-sh compatible so it can be invoked as:
# - sh script/test/generate_coverage_report.sh
# - bash script/test/generate_coverage_report.sh

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT="${SCRIPT_DIR}/COVERAGE.md"

list_scripts() {
  find "${REPO_ROOT}" \
    -type d \( -name .git -o -name node_modules -o -name vendor -o -name .terraform -o -name .venv \) -prune -o \
    -type f -name '*.sh' -print \
    | sed "s|^${REPO_ROOT}/||" \
    | sort
}

script_kind() {
  abs="$1"
  first="$(head -n 1 "$abs" 2>/dev/null || true)"
  case "$first" in
    '#!/bin/sh'|'#!/usr/bin/sh'|'#!/usr/bin/env sh') echo "sh" ;;
    '#!'*) echo "bash" ;;
    *) echo "unknown" ;;
  esac
}

coverage_for() {
  rel="$1"

  cov="script/test/test_smoke_repo_scripts.sh (syntax + static refs)"

  case "$rel" in
    script/*)
      case "$rel" in
        script/test/*) : ;;
        *) cov="${cov};script/test/test_smoke_all_scripts.sh (syntax + orchestrator refs in script/)" ;;
      esac
      ;;
  esac

  case "$rel" in
    script/13-Create_custom_schema_attr.sh) cov="${cov};script/test/test_custom_schema_attr.sh (LDAP integration)" ;;
    script/15-add-password-checker.sh) cov="${cov};script/test/test_password_checker.sh (LDAP integration)" ;;
    script/16-add-strong-password-quality-checker-PPM.sh) cov="${cov};script/test/test_password_complexity.sh (LDAP integration)" ;;
    script/17-create_mw_user.sh) cov="${cov};script/test/test_mw_service_user.sh (LDAP integration)" ;;
    script/18-service-account-password-policy-never-expire.sh) cov="${cov};script/test/test_service_account_password_policy_never_expire.sh (LDAP integration)" ;;
    script/19-create-user-using-mw-user.sh) cov="${cov};script/test/test_create_user_using_mw_user.sh (LDAP integration, runs script)" ;;
    script/22-tuning.sh) cov="${cov};script/test/test_tuning.sh (LDAP integration)" ;;
    script/23-ensure-installation-not-under-root.sh) cov="${cov};script/test/test_installation_not_under_root.sh (unit-ish, runs script)" ;;
    script/24-configure-ssl-tls.sh) cov="${cov};script/test/test_configure_ssl_tls.sh (LDAP integration)" ;;
    script/25-configure-accesslog-audit.sh) cov="${cov};script/test/test_accesslog_audit.sh (LDAP integration)" ;;
    script/26-configure-bindings.sh) cov="${cov};script/test/test_bindings.sh (LDAP integration, runs script)" ;;
  esac

  printf "%s\n" "$cov"
}

{
  echo "# Script Test Coverage"
  echo
  echo "This file is generated by \`script/test/generate_coverage_report.sh\`."
  echo
  echo "## Test Suites"
  echo
  echo "- \`script/test/test_smoke_all_scripts.sh\`: smoke test limited to the \`script/\` directory."
  echo "- \`script/test/test_smoke_repo_scripts.sh\`: repo-wide smoke test for all \`*.sh\` files (syntax + static orchestrator references)."
  echo "- \`script/test/run_all.sh\`: entrypoint; always runs smoke tests. Set \`RUN_LDAP_INTEGRATION_TESTS=1\` to run LDAP integration tests."
  echo
  echo "## Coverage Table"
  echo
  echo "| Script | Kind | Covered By |"
  echo "|---|---:|---|"

  list_scripts | while IFS= read -r rel; do
    abs="${REPO_ROOT}/${rel}"
    kind="$(script_kind "$abs")"
    covered="$(coverage_for "$rel" | tr '\n' ' ' | sed 's/[[:space:]]*$//')"
    covered_fmt="$(printf "%s" "$covered" | sed 's/;/; /g')"
    printf '| `%s` | `%s` | %s |\n' "$rel" "$kind" "$covered_fmt"
  done
} >"$OUT"

echo "[OK] Wrote $OUT"
