stages:
  - validate
  - deploy
  - test
  - destroy

variables:
  TF_ROOT: terraform/openldap-master-replica/instances

shellcheck:
  stage: validate
  image: koalaman/shellcheck-alpine:v0.10.0
  script:
    - shellcheck --severity=error script/*.sh

terraform-validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.10
    entrypoint: [""]
  script:
    - cd $TF_ROOT
    - terraform init -backend=false
    - terraform validate
